#!/usr/bin/env python2


import os
import sys


os.system("git config --global user.name yuvalnirhod")
os.system("git config --global user.email yuvalnirhod@mail.tau.ac.il")

os.system("git add .")
os.system("git commit -m {}".format(sys.argv[1]))
os.system("git push -u origin main")
